### ISSUE TITLE
TODO Bilder

### ISSUE THREAD

**Issue by knuthaug** [knuthaug/enduro-stats#14]
Generelt
* [x] Forsidebilde
* [x] s3 bucket
* [x] Cloudfront oppsett
* [x] Script for å laste opp til s3 og lagre til db for rytter (ogsp rename av bildet til uid)
* [x] cloudfront url i config
* [x] lagre bib i resultat-tabell

 Ritt
* [x] database-felter på ritt-tabell
 * byline
* [x] felt i racedata.json
* [x] support i import

Rytter
* [x]  databasefelter
 * byline

**Comment by knuthaug** [comment]
done
